<?php

$en1 = (array)$en_cmds = (object) [
    'help'              => "!help",
    'admin_help'        => "!admin help",
    'rules'             => "!rules",
    'all'               => "!all",
    'votekick'          => "!votekick",
    'nick_list'         => "!nicks",
    'test'              => "!test",
    'roulette'          => "!rr",
    'profile'           => "!profile",
    'shop'              => "!shop",
    'plus_rep'          => "+rep",
    'minus_rep'         => "-rep",
];
$ru1 = (array)$ru_cmds = (object) [
    'help'              => "!помощь",
    'rules'             => "!правила",
    'votekick'          => "!вотекик",
    'roulette'          => "!рулетка",
    'admin_list'        => "!админы",
    'nick_list'         => "!ники",
    'profile'           => "!профиль",
    'shop'              => "!шоп",
    'larek'             => "!ларек",
    'autos'             => "!автосалон",
    'butik'             => "!бутик",
    'bar'               => "!бар",
    'plus_rep'          => "+реп",
    'minus_rep'         => "-реп",
    'bonus'             => "!бонус",
    'gift'              => "!подарок",
    'casino'            => "!казино",
    'moneta'            => "!монетка",
    'top_mess'          => "!топ сообщений",
    'money_get_user'    => "!дать денег",
    'bandit'            => "!бандит",
];
$ru2 = (array)$ru_desc = (object) [
    'help'              => "Отобразить список команд",
    'rules'             => "Отобразить правила беседы",
    'votekick'          => "Начать голосование за кик пользователя (перешлите сообщение)",
    'roulette'          => "Испытать удачу в русской рулетке",
    'admin_list'        => "Список админов",
    'nick_list'         => "Список ников пользователей",
    'profile'           => "Показать информацию о себе",
    'shop'              => "Можно купить различные предметы",
    'plus_rep'          => "Повысить репутацию пользователя",
    'minus_rep'         => "Понизить репутацию пользователя",
    'bonus'             => "Получить бонус от чата",
    'gift'              => "Получить подарок от чата",
    'bar'               => "Зайти в бар",
    'autos'             => "Зайти в автосалон",
    'casino'            => "Сделать ставку (от 1/все)",
    'moneta'            => "Предложить сыграть в Орел и Решка (!монетка @id ставка)",
    'top_mess'          => "Показать топ сообщений",
    'butik'             => "Зайти в бутик",
    'larek'             => "Зайти в ларек",
    'money_get_user'    => "Передать деньги другому пользователю",
    'bandit'            => "Сыиграть в однорукого бандита",
];


$adm = (array)$admin_cmds_en = (object) [
    'nick_add'          => "!nick add",
    'nick_remove'       => "!nick remove",
    'clear'             => "!clear",
    'kick'              => "!kick",
    'warn'              => "!warn",
    'admin_add'         => "!admin add",
    'admin_remove'      => "!admin remove",
    'admin_list'        => "!admins",
    'show_secure'       => "!show secure",
    'show_active'       => "!show active",
    'show_unactive'     => "!show unactive",
    'secure_nude'       => "!secure nude",
    'secure_censor'     => "!secure censor",
    'secure_links'      => "!secure links",
    'secure_invites'    => "!secure invites",
    'secure_bots'       => "!secure bots",
    'secure_repost'     => "!secure repost",
    'secure'            => "!secure",
    'enable'            => "enable",
    'disable'           => "disable",
    'update'            => "!update",
    'warn_remove'       => "!unwarn",
    'mute_remove'       => "!unmute",
];
$adm_ru = (array)$admin_cmds_ru = (object) [
    'nick_add'          => "!ник добавить",
    'nick_remove'       => "!ник удалить",
    'clear'             => "!очистить",
    'kick'              => "!кик",
    'warn'              => "!варн",
    'admin_add'         => "!админ добавить",
    'admin_remove'      => "!админ удалить",
    'show_active'       => "!показать актив",
    'show_unactive'     => "!показать неактив",
    'warn_remove'       => "!анварн",
    'mute_remove'       => "!размут",
    'delmess'           => "удалить",
    'changerang'        => "!ранг",
    'who_invite'        => "!кто добавил",
    'mute'              => "!мут",
    'money_get'         => "!выдать денег",
    'money_take'        => "!забрать деньги",
];
$adm_ru2 = (array)$admin_cmds_ru_desc = (object) [
    'nick_add'          => "Добавить ник пользователю",
    'nick_remove'       => "Удалить ник пользователю",
    'clear'             => "Очистить чат",
    'kick'              => "Кикнуть пользователя из чата",
    'warn'              => "Выдать варн пользователю",
    'admin_add'         => "Добавить админа",
    'admin_remove'      => "Удалить админа",
    'show_active'       => "Показать активность пользователей",
    'show_unactive'     => "Показать неактивных пользователей",
    'warn_remove'       => "Снять варн",
    'mute_remove'       => "Снять мут",
    'delmess'           => "Удалить сообщение пользователя",
    'changerang'        => "Изменить ранг пользователю",
    'who_invite'        => "Показать, кто добавил пользователя",
    'mute'              => "Дать мут",
    'money_get'         => "Выдать денег",
    'money_take'        => "Забрать деньги",
];

$rp_cmds = (object)['обнять', 'ударить', 'поцеловать', 'пожать руку', 'кусь', 'пнуть', 'шлепнуть', 'дать пять'];
$commands = (object)array_merge_recursive($en1, $ru1, $adm, $adm_ru);
?>